module.exports = [
  "American gods",
  "Chernobyl",
  "Homeland",
  { name: "Game Of Thrones", res: "1080p" },
  "The Mandalorian",
  "Silicon valley",
  "Modern family",
  "Westworld",
  "Legion",
  "Last week tonight",
  "Suits",
  "The big bang theory",
  "This is us",
  "Watchmen",
  { name: "Star Trek Discovery", res: "1080p" },
  { name: "One Punch Man", res: "1080p", type: "manga" },
  { name: "Tate no Yuusha no Nariagari", res: "1080p", type: "manga" },
  { name: "Shingeki no Kyojin", res: "1080p", type: "manga" },
  { name: "Parasyte", res: "1080p", type: "manga" },
  { name: "Black Clover", res: "1080p", type: "manga" },
  { name: "Boku no Hero Academia", res: "1080p", type: "manga" },
  { name: "Violet Evergarden", res: "1080p", type: "manga" },
  { name: "Megalo Box", res: "1080p", type: "manga" },
  { name: "Dororo", res: "1080p", type: "manga" },
  { name: "Mob Psycho 100", res: "1080p", type: "manga" },
  "Rick and Morty"
];
